version: 2.1

orbs:
  # Replace this with your own!
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

executors:
  python:
    docker:
      - image: cimg/python:3.9
  base:
    docker:
      - image: cimg/base:stable


jobs:
  # Define one or more jobs which will utilize your orb's commands and parameters to validate your changes.
  integration-test-1:
    parameters:
      compute:
        description: What executor to use for the job
        type: executor
        default:
    executor: <<parameters.compute>>
    steps:
      - checkout
      - aws-elastic-beanstalk/setup
      - run:
          name: Verify EB install
          command: |
            command -v eb >/dev/null 2>&1 || { echo >&2 "EB cli failed to install or persist to the path"; exit 1; }
  integreation-test-deploy-setup:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - aws-elastic-beanstalk/setup
      - run:
          name: EB Create
          command: |
            cd sample_app
            eb init sample_app -r $AWS_DEFAULT_REGION -p Node.js

workflows:
  # Prior to producing a development orb (which requires credentials) basic validation, linting, and even unit testing can be performed.
  # This workflow will run on every commit
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148,SC2016,SC1090,SC1090
      # optional: Run BATS tests against your scripts
      - bats/run:
          path: ./src/tests
      # Publish development version(s) of the orb.
      - orb-tools/publish-dev:
          orb-name: circleci/aws-elastic-beanstalk
          context: orb-publishing # A restricted context containing your private publishing credentials. Will only execute if approved by an authorized user.
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - bats/run
            - shellcheck/check
      # Trigger an integration workflow to test the
      # dev:${CIRCLE_SHA1:0:7} version of your orb
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  # This `integration-test_deploy` workflow will only run
  # when the run-integration-tests pipeline parameter is set to true.
  # It is meant to be triggered by the "trigger-integration-tests-workflow"
  # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # Run any integration tests defined within the `jobs` key.
      - integration-test-1:
          context: [CPE_ORBS_AWS]
          matrix:
              parameters:
                compute: [python, base]
      - integreation-test-deploy-setup:
          context: [CPE_ORBS_AWS]
          requires:
              - integration-test-1
      - aws-elastic-beanstalk/deploy:
          post-steps:
              - run:
                  name: Test deployed app
                  working_directory: ./sample_app
                  command: curl $(eb status | grep CNAME | cut -d ":" -f 2)
          context: [CPE_ORBS_AWS]
          environment-name: eb-orb-testing
          label: test-label-<<pipeline.number>>
          app-dir: ./sample_app
          requires:
                - integreation-test-deploy-setup
      # Publish a semver version of the orb. relies on
      # the commit subject containing the text "[semver:patch|minor|major|skip]"
      # as that will determine whether a patch, minor or major
      # version will be published or if publishing should
      # be skipped.
      # e.g. [semver:patch] will cause a patch version to be published.
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: circleci/aws-elastic-beanstalk
          context: orb-publishing
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - integration-test-1
          filters:
            branches:
              only: master
