description: >
  A Docker image created by CircleCI with continuous delivery and deployment pipelines in mind.
  It contains the AWS CLI and other related tools.

parameters:
  tag:
    type: string
    default: "2023.05"
    description: >
      Select any of the available tags here: https://circleci.com/developer/images/image/cimg/aws.
  resource_class:
    description: Configure the executor resource class
    type: enum
    enum: ["small", "medium", "medium+", "large", "xlarge", "2xlarge", "2xlarge+"]
    default: "medium"

resource_class: << parameters.resource_class >>
docker:
  - image: cimg/aws:<< parameters.tag >>
