description: |
  Easily deploy your application to Elastic Beanstalk with the provided deploy job using OIDC for authentication.
  Import the aws-cli orb and authenticate using the aws-cli/setup command with a valid role-arn for OIDC authentication.
  This example shows how a Node.JS application may be tested and then deployed in a realistic CI environment, using both the Node orb and AWS Elastic Beanstalk orb.
  This assumes the EB environment already exists and is awaiting deployments.

usage:
  version: 2.1
  orbs:
    node: circleci/node@5.1.0
    eb: circleci/aws-elastic-beanstalk@3.0
    aws-cli: circleci/aws-cli@3.1
  workflows:
    elastic-beanstalk-workflow:
      jobs:
        - node/test # Automatically run Node tests via the Node orb.
        - eb/deploy: # If tests pass, and the commit is to the main branch, deploy to Elastic Beanstalk.
            auth:
              # Add authentication step with OIDC using aws-cli/setup command
              - aws-cli/setup:
                  profile: "OIDC-USER"
                  role-arn: "arn:aws:iam::123456789012:role/VALID_OIDC_CODEDEPLOY_ROLE"
            environment-name: my-app # It is assumed this environment has been created
            label: version-<<pipeline.number>>
            # Must use same profile configured in aws-cli/setup command
            profile: "OIDC-USER"
            # must use valid CircleCI context for OIDC authentication
            context: CircleCI_OIDC_Token
            requires:
              - node/test
            filters:
              branches:
                only:
                  - main
